NPM/Gulp failure fix
Overnight Gulp broke. Running `gulp` gave this error:

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/home/sybren/workspace/blender-id/node_modules/natives/index.js:137:5)
    at require (/home/sybren/workspace/blender-id/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/home/sybren/workspace/blender-id/node_modules/natives/index.js:137:5)
    at require (/home/sybren/workspace/blender-id/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/home/sybren/workspace/blender-id/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/sybren/workspace/blender-id/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/sybren/workspace/blender-id/node_modules/graceful-fs/fs.js:1:99)

Upgrading 'natives' to 1.1.6 helps work around this. See
https://github.com/gulpjs/gulp/issues/2162#issuecomment-385197164 for more
information.